### ISSUE TITLE
Portal component doesn't render outside the application root element (in Sanity studio)

### ISSUE THREAD

**Issue by robinpyon** [sanity-io/design#442]
### Describe the bug

When used within Sanity studio, `Portal` components don't appear to be rendering outside the studio / application root and are instead rendered in-line within the desk panel

### To Reproduce

- On a fresh studio install, create a dummy document schema with an image field
- Configure a custom asset source plugin (e.g. using [plugin-template-asset-source](https://github.com/sanity-io/plugin-template-asset-source))
- Wrap the contents of the custom asset source plugin in a `Portal` component

###  Expected behavior

The asset source plugin to render outside the application root

### Screenshots

**Starting state**
![image](https://user-images.githubusercontent.com/209129/109306023-7ae00180-7836-11eb-8e34-4fde1f8e8f6e.png)

**After the MyAssetSource button has been pressed**
Note that the contents of the portal sits nested inside `documentPanel_documentViewerContainer` and not outside the application root
![image](https://user-images.githubusercontent.com/209129/109306188-bbd81600-7836-11eb-8331-9ca552751cb3.png)

**Expected state (using a custom portal component)**
Portal contents sit outside `div#sanity` as expected
![image](https://user-images.githubusercontent.com/209129/109306372-ff328480-7836-11eb-8c1e-09b91ac79961.png)

### Which versions of Sanity are you using?

```
@sanity/cli             2.2.6 (latest: 2.4.0)
@sanity/base            2.4.3 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.4.0 (up to date)
@sanity/default-layout  2.4.3 (up to date)
@sanity/default-login   2.2.6 (up to date)
@sanity/desk-tool       2.4.3 (up to date)
@sanity/storybook       2.4.3 (up to date)
@sanity/vision          2.2.6 (up to date)
```

### Additional context

```
@sanity/ui              0.33.6
```

_Anecdotally_, I believe this worked prior to the studio shift in `~2.3.8`

**Comment by mariuslundgard** [comment]
Hi @robinpyon – this is intentional. Unfortunately (tho fortunately for us, so we could iron out as many issues as possible based on your input 🙏) you started implementing things in Sanity UI before the Desk tool itself had started using Sanity UI.

It’s possible to override the portal element context value, however, so you should be able to do something like:

```jsx
<PortalProvider element={document.body}>
  <Portal>This will be rendered in the provider portal element</Portal>
</PortalProvider>
```

Feel free to re-open this issue in https://github.com/sanity-io/sanity/issues if this is not a good solution for you.
