### ISSUE TITLE
Contents of a button given both children and text is not centered

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/design#471]
This is an edge case for sure, but if a Button is given both `text` and `children` that's not visible, it doesn't render centered content when filling available space horizontally. Although rarely needed, one use case for this is to create a file upload button which has a absolute positioned`<input type=file …` as child in order to trigger the select file dialog.

[Here's how](https://github.com/sanity-io/sanity/blob/e06b4ea154f3ea999e0b994e073ba346a695dc9a/packages/%40sanity/form-builder/src/inputs/files/common/FileInputButton/FileInputButton.tsx#L52-L57
) we're currently working around this issue in the Studio, but it would be good to have a more permanent solution for it.

Repro case: https://www.sanity.io/ui/arcade?mode=jsx&jsx=eJwtT0EKwjAQvPcVSy%2BFUghYT5IU1IN49igeghvbQN2UZgVryN%2BNqbAsw%2BwMMytPs8WuAJCHF7OjhAAejvhiP0aF66aBNO0t5oO9O1Jhj3hOYKWeDo0q%2B8F5LjMxaURLffK2ydjA9u9l82ZVHmej2azKLu8U7SdN4HkZU2JA66dRL7uKHJkqxi6IGgaLaAhqEaX4qXNjsVbuCinyF1%2BjlTwx&hook=eJwrSi0pLcpTqK7lAgAWpQPD&title=Button+example&description=A+basic+example+of+using+the+Button+primitive+in+Sanity+UI.

**Comment by mariuslundgard** [comment]
This is fixed only rendering `icon` and `text` if `children` is not provided, and will be released as part of the next release.

**Comment by mariuslundgard** [comment]
[See this arcade](https://www.sanity.io/ui/arcade?mode=jsx&jsx=eJxlkE1qwzAQhfc5hfDGy3QdJC9KCYTsAj2AYo1jhenI2GNqIXz3jhUnLkSrN9%2Bbn4f0EWHaKWXR38gUNRBDXwhowd9aNkXjEXPNP3gMfQawgPs4sG%2FiNlMJ1J8jcyBRsnIwBdor5HGlfB3IpO8Og3Un0XOmgc4Qv8KvWK0lh7CWD5ft9UQOJpM%2BVgATm5SlHKtWodRjrVqyvZj21I38KiWB29I%2FXw%2BNSbnxAs38z%2BDYwXv7wBHBpOT80KGNB1VSICjnbXL%2FDKVXtVgi9X756Wr3B9dlZR4%3D&hook=eJxdjb0KwjAUhfc8xdmSgOQNooM6ubmKQ423GHq5lTRRiu27G1pwcDuc7%2FyEXoaMKM%2BSz9TCowxUhZHCbJUKC340cmc60Xjo37Jm9g3zrQmdMfQiyRZ%2Bi48CYovVcR2N8N5DHyVT0pgm%2FAFou3Tw%2B3ehpFQzOxc41nFb6azmDS5Xq74qGjZA&title=Upload+button+example) for a reference of how to achieve a styled upload button.
