### ISSUE TITLE
Popover gets incorrect placement on subsequent renders

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/design#519]
When using the Sanity UI Popover for the Date input in the Sanity Studio ([code here](https://github.com/sanity-io/sanity/blob/ui/ch3348/date-inputs/packages/@sanity/form-builder/src/inputs/DateInputs/base/DateTimeInput.tsx#L56-L88)) the popover places itself incorrectly (and forces viewport scroll) on subsequent renders. It turned out to be tricky to create a small repro case of this outside of Studio context (tried to replicate in the [Arcade](https://www.sanity.io/ui/arcade?mode=jsx&width=0&jsx=eJxVUEFugzAQvOcVW5%2Bo1Mg0Ui8V5pBIUStVSg79AMVLcOvYyJgUavH3LoZK9IJndmZ2l82OGnv47FqvqkGwitgWjWT5BiA728be0BEEaKzzhY6wtMaj8SJERr63YkB3dvamJDr4OVVViyQ%2Fpmk65ouJbHFU6weNIoQa1aX2z%2FCUpg%2FwraSvIx5XAYrsbQ9NIaUyF8F2bK2R%2Bo69z19Qa5vxiNdRTtnVcD5N%2F%2BMZ%2F7fyXB7j1zZoRFDtid650uiixOv0w%2BzDem%2Bv8UBRcoVUXSvCbnLOXbJ9Rx4D1hy0Kr9ESO5B5EAHeY09k2TuHat3Cx7B0%2FqCTYTxeHu%2BHD%2FfLKv%2FAgAReos%3D&hook=eJxLzs8rLlGIziz2L0jN01EoTi3xBDNjFWwVglITk0v0SotTg0sSS1I10hJzilM1rbm4ilJLSovyFKoxNNVyAQBnoRv9), but it's not happening here), but the issue can be demonstrated in the screen recordings below.

Note that it doesn't happen on initial render.

https://user-images.githubusercontent.com/876086/111342991-44e6ae00-867b-11eb-859b-ebb8cef5d926.mov

https://user-images.githubusercontent.com/876086/111343012-49ab6200-867b-11eb-849a-7a925220112f.mov

**Comment by mariuslundgard** [comment]
Hey @bjoerge – I’m not sure if this is an issue with Sanity UI or Popper.js.

Can you try using this and see if that works better?

```tsx

<Popover
  fallbackPlacements={["top-end"]}
  placement="bottom-end"
 />
```
